import fs from "fs";

export function codeGenerator(plan, name = "pulse-app") {

  const base = `./output/${name}`;

  const folders = [
    "app/pages",
    "app/components",
    "app/api",
    "lib",
    "styles"
  ];

  folders.forEach(f => {
    fs.mkdirSync(`${base}/${f}`, { recursive: true });
  });

  // =========================
  // NEXT.JS HOME PAGE
  // =========================
  fs.writeFileSync(
    `${base}/app/pages/index.jsx`,
    `
export default function Home() {
  return (
    <main>
      <h1>${name}</h1>
      <p>Generated by Pulse AI</p>
    </main>
  );
}
`
  );

  // =========================
  // API ROUTE
  // =========================
  fs.writeFileSync(
    `${base}/app/api/health.js`,
    `
export default function handler(req, res) {
  res.status(200).json({ status: "ok", app: "${name}" });
}
`
  );

  // =========================
  // README
  // =========================
  fs.writeFileSync(
    `${base}/README.md`,
    `
# ${name}

Generated by Pulse AI v9

## Stack
Next.js + API Routes

## Features
${JSON.stringify(plan, null, 2)}
`
  );

  return {
    status: "generated",
    framework: "nextjs",
    path: base
  };
}