import fs from "fs";

export function projectGenerator(plan, name = "generated-app") {

  const basePath = `./output/${name}`;

  const structure = {
    frontend: ["pages", "components"],
    backend: ["routes", "controllers"],
    database: ["models"],
    config: []
  };

  // create folders
  Object.entries(structure).forEach(([dir, subdirs]) => {
    subdirs.forEach(sub => {
      const path = `${basePath}/${dir}/${sub}`;
      fs.mkdirSync(path, { recursive: true });
    });
  });

  // basic starter files
  fs.writeFileSync(
    `${basePath}/README.md`,
    `# ${name}\nGenerated by Pulse AI\n`
  );

  fs.writeFileSync(
    `${basePath}/backend/server.js`,
    `console.log("Backend started");`
  );

  fs.writeFileSync(
    `${basePath}/frontend/app.js`,
    `console.log("Frontend started");`
  );

  return {
    status: "generated",
    path: basePath
  };
}